# Task to provision the server
---
- name: Get elasticsearch key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present
  ignore_errors: True

- name: Add elasticsearch repository
  apt_repository: repo='deb http://packages.elasticsearch.org/elasticsearch/2.x/debian stable main' state=present
  ignore_errors: True

- name: Add Logstash repository
  apt_repository: repo='deb http://packages.elasticsearch.org/logstash/2.3/debian stable main' state=present
  ignore_errors: True

- name: Get public signing key for kibana
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch state=present
  ignore_errors: True

- name: Add Kibana repository
  apt_repository: repo='deb http://packages.elastic.co/kibana/4.5/debian stable main' state=present
  ignore_errors: True

- name: Update apt cache
  apt: update_cache=yes
  ignore_errors: True

- name: Update OS
  apt: upgrade=dist force=yes
  ignore_errors: True